---
- name: Install gunicorn
  yum: name=python-gunicorn state=present

- name: Copy service file
  copy: src=gunicorn.service dest=/etc/systemd/system/gunicorn.service
  notify: Systemctl Daemon reload

- name: Start gunicorn service
  service: name=gunicorn state=started
