---
- name: Install gunicorn
  package: name=python-gunicorn state=present

- name: Copy service file
  copy: src=gunicorn.service dest=/etc/systemd/system/gunicorn.service

- name: Start gunicorn service
  service: name=gunicorn state=started daemon_reload=yes
