---
- name: Install pip
  package: name=python-pip state=present

- name: Install Blogstrap
  pip: name=Blogstrap state=present

- name: Create /var/www
  file: path=/var/www state=directory

- name: Clone Shellinthecloud
  git: repo={{ blogstrap_git }} dest=/var/www/shellinthecloud force=yes
  notify: give read permission
